### ISSUE TITLE
Database error: "no such table: accounts"

### ISSUE THREAD

**Issue by louneskmt** [lnbits/lnbits#129]
Hi!

I made a docker image of LNbits (repo [here](https://github.com/louneskmt/docker-lnbits)) to use it with docker-compose.

My docker-compose service looks like that:
```
        lnbits:
                container_name: lnbits
                image: louneskmt/lnbits:latest
                logging: *default-logging
                depends_on: [ lnd ]
                restart: on-failure
                ports:
                    - "5000:5000"
                environment:
                    LNBITS_BACKEND_WALLET_CLASS: LndWallet
                    LND_GRPC_ENDPOINT: 10.11.1.2
                    LND_GRPC_PORT: 10009
                    LND_GRPC_CERT: "/lnd/tls.cert"
                    LND_GRPC_MACAROON: "/lnd/data/chain/bitcoin/mainnet/admin.macaroon"
                volumes:
                    - ${PWD}/lnd:/lnd:ro
                    - ${PWD}/apps/lnbits/.env:/lnbits/.env
                    - ${PWD}/apps/lnbits:/data
                networks:
                    net:
                        ipv4_address: 10.11.9.0
```
And in my `.env` file I've ``LNBITS_DATA_FOLDER="/data"``.

But when I try to add a wallet, this error appears:
```
...
lnbits               | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: accounts
lnbits               | [SQL: INSERT INTO accounts (id) VALUES (?)]
lnbits               | [parameters: ('05a7aa654a1f45e488b7deebf69bf2b8',)]
lnbits               | (Background on this error at: http://sqlalche.me/e/13/e3q8)
```
(But the file `database.sqlite3` has been created in my directory `apps/lnbits`.

It was working well before the env variable `LNBITS_DATA_FOLDER` was set to `/data` (but there was no persistence).

Any ideas on how I can solve this?

**Comment by fiatjaf** [comment]
How is the app being started? Depending on how, you may have to run migrations and asset generation commands before.

**Comment by louneskmt** [comment]
My docker container has an entrypoint starting the app with the documentation command:
https://github.com/louneskmt/docker-lnbits/blob/main/entrypoint.sh
```
#!/bin/sh -e

cd /lnbits
python3 -m venv venv
./venv/bin/hypercorn -k trio --bind 0.0.0.0:${PORT} 'lnbits.app:create_app()'
```

Migrations and assets generation are handled in the image build: https://github.com/louneskmt/docker-lnbits/blob/main/Dockerfile

**Comment by fiatjaf** [comment]
Can you manually open the database and check if the tables are actually there?

Also on startup LNbits should print the database path it is actually using. Maybe it is running the wrong path for some reason.

**Comment by louneskmt** [comment]
> Can you manually open the database and check if the tables are actually there?

The database seems to be empty:
```
/data # sqlite3 database.sqlite3 
SQLite version 3.32.1 2020-05-25 16:19:56
Enter ".help" for usage hints.
sqlite> .tables
sqlite> .show
        echo: off
         eqp: off
     explain: auto
     headers: off
        mode: list
   nullvalue: ""
      output: stdout
colseparator: "|"
rowseparator: "\n"
       stats: off
       width: 
    filename: database.sqlite3
```
And on startup, the path is not printed, just:
```
[2020-12-10 08:11:14 +0000] [11] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
```
But it seems correct, because when I try create a new LNbits wallet, the file `database.sqlite3` is well generated under the `/data` directory.
