### ISSUE TITLE
LNURLp address behind a HTTPS reverse proxy

### ISSUE THREAD

**Issue by btcforevercat** [lnbits/lnbits#1475]
Hi,

I use lnbits with Umbrel on a VPS. And I would like to access my lnbits site with https without Tor.
So I have installed a nginx reverse proxy on the same machine with a custom domain lightning.mydomain.com.
I have the following nginx conf :
 location / {
        proxy_pass http://XX.XX.XX.XX:3007;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_http_version 1.1;
    }

The lnbits access https://lightning.mydomain.com works.
But when I want to generate LNURLp address. The LNURL value is without SSL (ex: http://lightning.mydomain.com/lnurlp/api/v1/lnurl/1 with fiatjaf decoder).
So the address is rejected by BlueWallet (I think it is because it is not https).

Do you know what I am missing, to have LNURLp with https ?

Regards,

**Comment by dni** [comment]
``` FORWARDED_ALLOW_IPS="*"``` inside env aswell

**Comment by btcforevercat** [comment]
I use Umbrel and there is no .env file in ~/umbrel/app-data/lnbits.
Is it the .env file located in the ~/umbrel folder ?

**Comment by schneimi** [comment]
> I use Umbrel and there is no .env file in ~/umbrel/app-data/lnbits. Is it the .env file located in the ~/umbrel folder ?

You can set the env var in `umbrel/app-data/lnbits/docker-compose.yml`.

**Comment by btcforevercat** [comment]
I updated my ~/umbrel/app-data/lnbits/docker-compose.yml like below, and it does not work :
```
version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lnbits_web_1
      APP_PORT: 3007
      PROXY_AUTH_ADD: "false"
      FORWARDED_ALLOW_IPS: "*"

  web:
    image: lnbitsdocker/lnbits-legend:0.9.7@sha256:1fccd9611a23b9d9259ca4adff860e3e2d441ed42261d192141e76b261cd3b74
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
    environment:
      # Global
      LNBITS_HOST: "0.0.0.0"
      LNBITS_PORT: 3007
      LNBITS_FORWARDED_ALLOW_IPS: "*"
      FORWARDED_ALLOW_IPS: "*"
      LNBITS_DATA_FOLDER: "/data"

      # LND
      LNBITS_BACKEND_WALLET_CLASS: LndRestWallet
      LND_REST_ENDPOINT: https://$APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_REST_PORT/
      LND_REST_CERT: "/lnd/tls.cert"
      LND_REST_MACAROON: "/lnd/data/chain/bitcoin/$APP_BITCOIN_NETWORK/admin.macaroon"

      # App
      LNBITS_SITE_TITLE: "LNbits - Umbrel"
      LNBITS_DEFAULT_WALLET_NAME: "LNbits wallet"
      LNBITS_DISABLED_EXTENSIONS: "amilk"
      LNBITS_ADMIN_EXTENSIONS: "ngrok"
```
