### ISSUE TITLE
[BUG] TLS for REST RPC for LND Failed

### ISSUE THREAD

**Issue by dell1503** [lnbits/lnbits#2084]
**Describe the bug**
LNBits gets the following error when connecting to LND REST: 
`| ERROR | Error connecting to LndRestWallet: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1007)`

**Setup**: Docker-Compose with LightningD (LND) and LNBITS.
I pulled the latest version of both Respositories, and use that to Build the Docker Container.

Find bellow my Docker-Compose File:
```
version: '3'
services:
  lnbits:
    build: ./lnbits
    image: lnbits/lnbits:latest
    ports:
      - "5000:5000"
    networks:
      - ln_network
    depends_on:
      - lnd
    volumes:
      - lnbits-data:/app/data
      - lnd-data:/root/.lnd
    links:
      - "lnd:lnd"

  lnd:
    build: ./lnd
    image: lightningnetwork/lnd:latest
    command:
      - "--bitcoin.mainnet"
      - "--bitcoin.active"
      - "--bitcoin.node=neutrino"
      - "--neutrino.addpeer=btcd-mainnet.lightning.computer"
      - "--neutrino.addpeer=mainnet1-btcd.zaphq.io"
      - "--feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json"
      - "--debuglevel=info"
      - "--wallet-unlock-password-file=/root/.lnd/password.txt"
      - "--restlisten=0.0.0.0:8080"
      - "--tlsextradomain=lnd"
      - "--tlsextradomain=lnd.local"

    ports:
      - "9735:9735"
      - "10009:10009"
      - "8080:8080"
    hostname: lnd
    networks:
      - ln_network
    volumes:
      - lnd-data:/root/.lnd

volumes:
  lnbits-data:
  lnd-data:

networks:
  ln_network:
```

I mount the .lnd Data fulder to Lnbits. This allows me to directly configure in .env the LND as follow:
# LndRestWallet
LND_REST_ENDPOINT=https://lnd:8080/
LND_REST_CERT="/root/.lnd/tls.cert"
LND_REST_MACAROON="/root/.lnd/data/chain/bitcoin/mainnet/admin.macaroon"

I See this Value in the Log Files when starting the LNBits Container.

**To Reproduce**

Remove the cert. before hand, to force re-creation.
Always happens when I run docker-compose up.

**Expected behavior**
Connection from LNBits to LND REST API works.

**Screenshots**
-

**Desktop (please complete the following information):**

- LNbits version:  0.11.2
- LND Version: 0.17.0-beta commit=tlv/v1.1.2
- Default - SQLite
**Additional context**
I think the Error comes as it is a self Sign Certificate. Is there a option to accept this?

Thank you!
